version: '3.8'

networks:
  default:
    external: true
    name: ${NETWORK}

volumes:
  cassandra_data: # For TheHive
  elasticsearch_data: # For TheHive and Cortex
  minio_data: # For TheHive

services:
  # === TheHive Components ===
  cassandra:
    image: 'cassandra:latest'
    container_name: ${COMPOSE_PROJECT_NAME}_cassandra
    hostname: cassandra
    mem_limit: ${CASSANDRA_MEM_LIMIT}
    ports:
      - "${CASSANDRA_PORT}:9042"
    environment:
      - MAX_HEAP_SIZE=${CASSANDRA_MAX_HEAP_SIZE}
      - HEAP_NEWSIZE=${CASSANDRA_HEAP_NEWSIZE}
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - cassandra_data:/var/lib/cassandra
    restart: unless-stopped
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q '^UN'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
    hostname: elasticsearch
    mem_limit: ${ELASTICSEARCH_MEM_LIMIT}
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
      - "${ELASTICSEARCH_NODES_PORT}:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD_FILE=/run/secrets/elastic_password
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ../../secrets/elastic_password:/run/secrets/elastic_password:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  minio:
    image: quay.io/minio/minio:latest
    container_name: ${COMPOSE_PROJECT_NAME}_minio
    hostname: minio
    mem_limit: ${MINIO_MEM_LIMIT}
    command: ["server", "/data", "--console-address", ":9090"]
    environment:
      - MINIO_ROOT_USER_FILE=/run/secrets/minio_root_user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio_root_password
    ports:
      - "${MINIO_PORT}:9000"  # Changed from 9000 to avoid conflict with TheHive
      - "${MINIO_CONSOLE_PORT}:9090"   # Minio console
    volumes:
      - minio_data:/data
      - ../../secrets/minio_root_user:/run/secrets/minio_root_user:ro
      - ../../secrets/minio_root_password:/run/secrets/minio_root_password:ro
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  cortex:
    image: thehiveproject/cortex:latest
    container_name: ${COMPOSE_PROJECT_NAME}_cortex
    hostname: cortex
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - job_directory=/tmp/cortex-jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/cortex-jobs:/tmp/cortex-jobs
    ports:
      - "${CORTEX_PORT}:9001"
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/api/status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  thehive:
    image: strangebee/thehive:5.2.7-1
    container_name: ${COMPOSE_PROJECT_NAME}_thehive
    hostname: thehive
    depends_on:
      cassandra:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      minio:
        condition: service_healthy
      cortex:
        condition: service_healthy
    mem_limit: ${THEHIVE_MEM_LIMIT}
    ports:
      - "${THEHIVE_PORT}:9000"
    environment:
      - JVM_OPTS=${THEHIVE_JVM_HEAP}
    volumes:
      - ./thehive-application.conf:/etc/thehive/application.conf:ro
      - ../../secrets/thehive_secret:/run/secrets/thehive_secret:ro
      - ../../secrets/minio_root_user:/run/secrets/minio_root_user:ro
      - ../../secrets/minio_root_password:/run/secrets/minio_root_password:ro
      - ../../secrets/cortex_api_key:/run/secrets/cortex_api_key:ro
    command:
      - --secret-file
      - /run/secrets/thehive_secret
      - "--cql-hostnames"
      - "cassandra"
      - "--index-backend"
      - "elasticsearch"
      - "--es-hostnames"
      - "elasticsearch"
      - "--s3-endpoint"
      - "http://minio:9000"
      - "--s3-access-key-file"
      - "/run/secrets/minio_root_user"
      - "--s3-secret-key-file"
      - "/run/secrets/minio_root_password"
      - "--s3-bucket"
      - "thehive"
      - "--s3-use-path-access-style"
      - "--cortex-hostnames"
      - "cortex"
      - "--cortex-keys-file"
      - "/run/secrets/cortex_api_key"
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
