version: '3.8'

networks:
  ${NETWORK}:
    external: true

services:
  # Integration helper
  integration-api:
    image: nginx:alpine
    container_name: cti-integration-api
    restart: unless-stopped
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../../integrations:/usr/share/nginx/html:ro
    ports:
      - "8888:80"
    networks:
      - ${NETWORK}
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/status"]
      interval: 30s
      timeout: 5s
      retries: 3
