version: '3.8'

networks:
  default:
    external: true
    name: ${NETWORK}

volumes:
  misp_data: # For MISP
  redis_data: # For Redis persistence

services:
  # === MISP Components ===
  misp-core:
    image: ghcr.io/misp/misp-docker/misp-core:latest
    container_name: ${COMPOSE_PROJECT_NAME}_misp-core
    hostname: misp
    ports:
      - "8083:80"     # Changed from 8080:80 to avoid conflict with Gophish
      - "8443:443"    # Changed from 443:443 to avoid conflict with Kasm Workspaces
    environment:
      - MYSQL_HOST=${COMPOSE_PROJECT_NAME}_misp-db
      - MYSQL_DATABASE=misp
      - MYSQL_USER=misp
      - MYSQL_PASSWORD_FILE=/run/secrets/misp_mysql_password
      - MISP_ADMIN_EMAIL=admin@example.com
      - MISP_ADMIN_PASSWORD_FILE=/run/secrets/misp_admin_password
      - REDIS_FQDN=${COMPOSE_PROJECT_NAME}_redis
    volumes:
      - misp_data:/var/www/MISP/app/files
      - ../../secrets/misp_mysql_password:/run/secrets/misp_mysql_password:ro
      - ../../secrets/misp_admin_password:/run/secrets/misp_admin_password:ro
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    depends_on:
      - misp-db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/users/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  misp-modules:
    image: ghcr.io/misp/misp-docker/misp-modules:latest
    container_name: ${COMPOSE_PROJECT_NAME}_misp-modules
    restart: unless-stopped
    environment:
      - REDIS_BACKEND=${COMPOSE_PROJECT_NAME}_redis
    depends_on:
      - redis
      - misp-core
    networks:
      - default
    security_opt:
      - no-new-privileges:true

  misp-db:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME}_misp-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/misp_root_password
      - MYSQL_DATABASE=misp
      - MYSQL_USER=misp
      - MYSQL_PASSWORD_FILE=/run/secrets/misp_mysql_password
    volumes:
      - misp_data:/var/lib/mysql
      - ../../secrets/misp_root_password:/run/secrets/misp_root_password:ro
      - ../../secrets/misp_mysql_password:/run/secrets/misp_mysql_password:ro
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "misp", "-p$$(cat /run/secrets/misp_mysql_password)"]
      interval: 5s
      timeout: 5s
      retries: 10
    # Fix for MySQL 8.0 initialization issue
    command:
      - --default-authentication-plugin=mysql_native_password
      - --skip-host-cache
      - --innodb_use_native_aio=0

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
